export enum HTTP_METHODS {
  POST = "POST",
  PUT = "PUT",
  GET = "GET",
  PATCH = "PATCH",
  DELETE = "DELETE",
}

export enum ROLES_GUESTSCAN {
  ADMIN = "ADMIN",
  CUSTOMER = "CUSTOMER",
  BUSINESS = "BUSINESS",
}

export enum STATUS_RESERVATIONS {
  PENDING = "PENDING",
  CANCELLED = "CANCELLED",
  NO_SHOW = "NO_SHOW",
  CONFIRMED = "CONFIRMED",
}

export enum BUSINESS_CLIENT_INVITATION_STATUS {
  INVITED = "INVITED",
  ACCEPTED = "ACCEPTED",
  REJECTED = "REJECTED",
}

export enum ROLES_GUESTSCAN_STAFF_BUSINESS {
  OWNER = "OWNER",
  RECEPTIONIST = "RECEPTIONIST",
  EMPLOYEE = "EMPLOYEE",
}
